const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const exe = b.addExecutable(.{
        .name = "rambit",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/main.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{
                .{ .name = "builtin_ramblers", .module = embedRamblers(b) },
            },
        }),
    });
    b.installArtifact(exe);

    const run_cmd = b.addRunArtifact(exe);
    run_cmd.step.dependOn(b.getInstallStep());
    if (b.args) |args| run_cmd.addArgs(args);
    const run_step = b.step("run", "Run rambit (e.g. `zig build run -- cat`)");
    run_step.dependOn(&run_cmd.step);

    const tests = b.addTest(.{ .root_module = exe.root_module });
    const test_step = b.step("test", "Run unit tests, including validation of every built-in rambler");
    test_step.dependOn(&b.addRunArtifact(tests).step);

    // Validates the files on disk rather than the embedded copies, so that
    // contributors get file paths they can open in error messages.
    const validate_cmd = b.addRunArtifact(exe);
    validate_cmd.setCwd(b.path("."));
    validate_cmd.addArgs(&.{ "validate", "ramblers" });
    const validate_step = b.step("validate", "Validate every rambler under ramblers/");
    validate_step.dependOn(&validate_cmd.step);
}

/// Scans `ramblers/` and produces a module that embeds every rambler's
/// assets, so that adding a rambler never requires touching any code.
///
/// The generated module exposes `entries: []const Entry`, where each entry
/// is one rambler directory and its `manifest.json` / `*.sprite` files.
fn embedRamblers(b: *std.Build) *std.Build.Module {
    const io = b.graph.io;
    const wf = b.addWriteFiles();

    var src: std.Io.Writer.Allocating = .init(b.allocator);
    const w = &src.writer;
    w.writeAll(
        \\//! Generated by build.zig from the contents of `ramblers/`. Do not edit.
        \\
        \\pub const File = struct { name: []const u8, data: []const u8 };
        \\pub const Entry = struct { id: []const u8, files: []const File };
        \\
        \\pub const entries: []const Entry = &.{
        \\
    ) catch @panic("OOM");

    var root = b.build_root.handle.openDir(io, "ramblers", .{ .iterate = true }) catch |err|
        std.process.fatal("unable to open ramblers/: {t}", .{err});
    defer root.close(io);

    for (sortedNames(b, root, .directory)) |id| {
        var dir = root.openDir(io, id, .{ .iterate = true }) catch |err|
            std.process.fatal("unable to open ramblers/{s}: {t}", .{ id, err });
        defer dir.close(io);

        w.print("    .{{ .id = \"{s}\", .files = &.{{\n", .{id}) catch @panic("OOM");
        for (sortedNames(b, dir, .file)) |name| {
            const sub_path = b.fmt("{s}/{s}", .{ id, name });
            _ = wf.addCopyFile(b.path(b.fmt("ramblers/{s}", .{sub_path})), sub_path);
            w.print("        .{{ .name = \"{s}\", .data = @embedFile(\"{s}\") }},\n", .{ name, sub_path }) catch @panic("OOM");
        }
        w.writeAll("    } },\n") catch @panic("OOM");
    }
    w.writeAll("};\n") catch @panic("OOM");

    return b.createModule(.{ .root_source_file = wf.add("builtin_ramblers.zig", src.written()) });
}

fn isAsset(name: []const u8) bool {
    return std.mem.eql(u8, name, "manifest.json") or std.mem.endsWith(u8, name, ".sprite");
}

/// Returns the names of the entries of `kind` in `dir`, sorted so that the
/// generated module (and `rambit list`) is deterministic. Hidden entries are
/// skipped, and so are files other than assets: they are never embedded, so
/// they may be called anything. The names that are kept end up in string
/// literals and file paths, so they are restricted to a conservative
/// character set (escaping would not do: `addCopyFile` takes `\` for a path
/// separator).
fn sortedNames(b: *std.Build, dir: std.Io.Dir, kind: std.Io.File.Kind) []const []const u8 {
    const io = b.graph.io;
    var names: std.ArrayList([]const u8) = .empty;
    var it = dir.iterate();
    while (it.next(io) catch |err| std.process.fatal("unable to scan ramblers/: {t}", .{err})) |entry| {
        if (entry.kind != kind or entry.name[0] == '.') continue;
        if (kind == .file and !isAsset(entry.name)) continue;
        for (entry.name) |c| switch (c) {
            'a'...'z', 'A'...'Z', '0'...'9', '-', '_', '.' => {},
            else => std.process.fatal("unsupported file name in ramblers/: '{s}'", .{entry.name}),
        };
        names.append(b.allocator, b.dupe(entry.name)) catch @panic("OOM");
    }
    std.mem.sort([]const u8, names.items, {}, lessThan);
    return names.items;
}

fn lessThan(_: void, a: []const u8, b: []const u8) bool {
    return std.mem.lessThan(u8, a, b);
}
