#!/usr/bin/env python3
"""Generates src/vt/width_table.zig, the cell widths of code points.

Run it from the repository root:

    python3 tools/width_table.py > src/vt/width_table.zig

It uses only the Python standard library, so the Unicode version of the
table is that of the unicodedata module of the Python running it.

The rules, first match wins, for U+00A0..U+10FFFF without surrogates:

1. Unassigned (Cn): 2 inside the blocks and planes that default to wide,
   else 1. Python reports east_asian_width 'F' for unassigned code points,
   so it is never trusted for them.
2. The soft hyphen and the prepended concatenation marks: 1, as they are
   visible although they are format characters.
3. Hangul medial vowels and final consonants: 0, as they join the
   leading consonant before them.
4. Nonspacing and enclosing marks and format characters (Mn, Me, Cf): 0.
5. East Asian wide or fullwidth, plus the ranges glibc also makes wide: 2.
6. Anything else, ambiguous width included: 1.

Only the ranges of widths 0 and 2 are written, merged.
"""
import sys
import unicodedata

# Unassigned code points in these blocks and planes default to wide (EastAsianWidth.txt).
DEFAULT_WIDE = [(0x3400, 0x4DBF), (0x4E00, 0x9FFF), (0xF900, 0xFAFF), (0x20000, 0x2FFFD), (0x30000, 0x3FFFD)]
# Format characters that are visible: the soft hyphen and the prepended concatenation marks.
VISIBLE_FORMAT = {0x00AD, 0x0600, 0x0601, 0x0602, 0x0603, 0x0604, 0x0605, 0x06DD, 0x070F, 0x0890, 0x0891, 0x08E2, 0x110BD, 0x110CD}
# Wide in glibc although not East Asian wide: circled numbers on black squares, Yijing hexagrams.
GLIBC_WIDE = [(0x3248, 0x324F), (0x4DC0, 0x4DFF)]


def width(cp):
    ch = chr(cp)
    category = unicodedata.category(ch)
    if category == "Cn":
        return 2 if any(lo <= cp <= hi for lo, hi in DEFAULT_WIDE) else 1
    if cp in VISIBLE_FORMAT:
        return 1
    if 0x1160 <= cp <= 0x11FF or 0xD7B0 <= cp <= 0xD7FF:  # Hangul vowels and final consonants
        return 0
    if category in ("Mn", "Me", "Cf"):
        return 0
    if unicodedata.east_asian_width(ch) in ("W", "F") or any(lo <= cp <= hi for lo, hi in GLIBC_WIDE):
        return 2
    return 1


def ranges(w):
    out = []
    for cp in range(0xA0, 0x110000):
        if 0xD800 <= cp <= 0xDFFF or width(cp) != w:
            continue
        if out and out[-1][1] == cp - 1:
            out[-1][1] = cp
        else:
            out.append([cp, cp])
    return out


def main():
    w = sys.stdout.write
    w("//! Generated by tools/width_table.py from the Unicode Character Database\n")
    w(f"//! {unicodedata.unidata_version}, as shipped with Python {sys.version_info.major}.{sys.version_info.minor}. Do not edit.\n")
    w("//! Code points that take up no cells or two; all others take up one.\n\n")
    w(f'pub const unicode_version = "{unicodedata.unidata_version}";\n')
    for name, value in (("zero", 0), ("wide", 2)):
        w(f"\npub const {name} = [_][2]u21{{\n")
        for lo, hi in ranges(value):
            w(f"    .{{ 0x{lo:04X}, 0x{hi:04X} }},\n")
        w("};\n")


main()
